"""
Day 2 tests — Middleware Interceptor

Tests:
  1. EmbeddingService — produces a 384-dim normalized vector
  2. TokenUsage extraction — works from usage_metadata
  3. Full intercepted run — IterationLog rows written to SQLite
  4. Researcher embeddings retrievable from DB after a run
"""

from __future__ import annotations

import asyncio
import uuid
from pathlib import Path

import pytest
import numpy as np

from engine.interceptor.embeddings import EmbeddingService
from engine.interceptor.token_counter import TokenUsage, extract_token_usage
from langchain_core.messages import AIMessage


# ── Embedding tests ────────────────────────────────────────────────────────────

class TestEmbeddingService:
    def test_embed_returns_384_dim_vector(self):
        svc = EmbeddingService()
        vec = svc.embed("Solar energy is generated by photovoltaic panels.")
        assert len(vec) == 384
        assert all(isinstance(v, float) for v in vec)

    def test_embed_empty_string_returns_zero_vector(self):
        svc = EmbeddingService()
        vec = svc.embed("")
        assert len(vec) == 384
        assert all(v == 0.0 for v in vec)

    def test_embed_normalized(self):
        """Vectors should be unit-length (cosine similarity = dot product)."""
        svc = EmbeddingService()
        vec = svc.embed("Climate change is caused by greenhouse gas emissions.")
        norm = float(np.linalg.norm(vec))
        assert abs(norm - 1.0) < 1e-4, f"Expected unit vector, got norm={norm:.4f}"

    def test_similar_texts_have_high_cosine_similarity(self):
        """Two semantically similar texts should have high cosine similarity (>0.8)."""
        svc = EmbeddingService()
        v1 = np.array(svc.embed("Solar energy is generated by photovoltaic panels."))
        v2 = np.array(svc.embed("PV panels convert sunlight to electricity."))
        similarity = float(np.dot(v1, v2))
        assert similarity > 0.7, f"Expected high similarity for related texts, got {similarity:.4f}"

    def test_different_texts_have_lower_similarity(self):
        """Semantically different texts should have lower cosine similarity (<0.5)."""
        svc = EmbeddingService()
        v1 = np.array(svc.embed("Solar panels convert sunlight to electricity."))
        v2 = np.array(svc.embed("GDP impact coefficients for agricultural subsidies per country."))
        similarity = float(np.dot(v1, v2))
        assert similarity < 0.7, f"Expected lower similarity for unrelated texts, got {similarity:.4f}"


# ── Token counter tests ────────────────────────────────────────────────────────

class TestTokenCounter:
    def test_extract_from_usage_metadata(self):
        """Should read from usage_metadata (LangChain unified format)."""
        msg = AIMessage(
            content="test",
            usage_metadata={"input_tokens": 150, "output_tokens": 75, "total_tokens": 225},
        )
        usage = extract_token_usage(msg)
        assert usage.prompt_tokens == 150
        assert usage.completion_tokens == 75
        assert usage.total_tokens == 225

    def test_returns_zeros_for_missing_metadata(self):
        """Should not raise — returns zero usage when metadata is absent."""
        msg = AIMessage(content="no metadata here")
        usage = extract_token_usage(msg)
        assert usage.prompt_tokens == 0
        assert usage.completion_tokens == 0

    def test_token_usage_addition(self):
        u1 = TokenUsage(100, 50)
        u2 = TokenUsage(200, 75)
        total = u1 + u2
        assert total.prompt_tokens == 300
        assert total.completion_tokens == 125
        assert total.total_tokens == 425


# ── Intercepted run integration test ──────────────────────────────────────────

@pytest.mark.asyncio
async def test_intercepted_run_writes_db_rows():
    """
    Full integration: run the intercepted graph and verify IterationLog rows
    are written to SQLite with embeddings.
    """
    from engine.storage.db import init_db, get_session_factory
    from engine.storage.models import IterationLog, Run
    from engine.interceptor.log_store import LogStore
    from engine.interceptor.hooks import InterceptorContext, flush_pending_logs
    from engine.agentic_graph.graph import build_graph
    from engine.agentic_graph.state import AgentState
    from sqlalchemy import select

    await init_db()

    corpus_dir = Path(__file__).parents[3] / "data" / "corpus"
    corpus_docs: list[str] = []
    if corpus_dir.exists():
        corpus_docs = [f.read_text() for f in sorted(corpus_dir.glob("*.md"))]

    run_id = str(uuid.uuid4())
    factory = get_session_factory()

    async with factory() as db:
        log_store = LogStore(db=db, run_id=run_id)
        await log_store.create_run(query="What is solar energy?")
        await db.flush()

        # Build intercepted graph (no log_store needed in context anymore)
        ctx = InterceptorContext(run_id=run_id)
        graph = build_graph(interceptor_ctx=ctx)

        state: AgentState = {
            "query": "What is solar energy and how do photovoltaic panels work?",
            "corpus_docs": corpus_docs or [
                "Solar energy is generated by photovoltaic panels that convert sunlight to electricity."
            ],
            "research_notes": "",
            "critique": "",
            "draft": "",
            "final_output": "",
            "iteration_count": 0,
            "circuit_breaker_triggered": False,
            "messages": [],
        }

        result = graph.invoke(state, config={"recursion_limit": 6})

        # Flush all in-memory pending logs to DB in one async batch
        await flush_pending_logs(ctx, db)

        await log_store.finalize_run(
            status="completed",
            iterations=result["iteration_count"],
            final_output=result["final_output"],
        )
        await db.commit()

        # Verify the Run row
        run_row = (await db.execute(select(Run).where(Run.id == run_id))).scalar_one()
        assert run_row.status == "completed"
        assert run_row.iterations >= 1

        # Verify IterationLog rows
        logs = (await db.execute(
            select(IterationLog)
            .where(IterationLog.run_id == run_id)
            .order_by(IterationLog.iteration)
        )).scalars().all()

        assert len(logs) >= 1, "Expected at least one IterationLog row"

        # Find researcher row and check embedding
        researcher_logs = [l for l in logs if l.node == "researcher"]
        assert len(researcher_logs) >= 1, "Expected at least one researcher log"
        assert researcher_logs[0].embedding_dim == 384, "Expected 384-dim embedding"
        assert researcher_logs[0].get_embedding() is not None

        # Verify embedding retrieval path (for Day 3)
        embeddings = await log_store.get_researcher_embeddings(last_n=5)
        assert len(embeddings) >= 1
        assert len(embeddings[0]) == 384

