"""
Basic tests for the Researcher → Critic → Writer graph (Day 1).

These tests use LLM_PROVIDER=mock so no API calls are made.
They verify that:
  1. The graph compiles without errors
  2. A normal query completes (Critic says SATISFIED eventually)
  3. An adversarial query hits GraphRecursionError at the configured limit
"""

from __future__ import annotations

import pytest
from langgraph.errors import GraphRecursionError

from engine.agentic_graph.graph import build_graph
from engine.agentic_graph.state import AgentState


def _make_initial_state(query: str) -> AgentState:
    return {
        "query": query,
        "corpus_docs": [
            "Solar energy is generated by photovoltaic panels that convert sunlight to electricity.",
            "Wind turbines convert kinetic energy from moving air into electricity.",
            "The circuit breaker pattern prevents cascade failures in distributed systems.",
        ],
        "research_notes": "",
        "critique": "",
        "draft": "",
        "final_output": "",
        "iteration_count": 0,
        "circuit_breaker_triggered": False,
        "messages": [],
    }


def test_graph_compiles() -> None:
    """The graph should compile without raising any errors."""
    graph = build_graph()
    assert graph is not None


def test_adversarial_query_crashes_at_recursion_limit() -> None:
    """
    An adversarial query (specific data not in corpus) must raise
    GraphRecursionError — this proves the baseline failure mode.
    """
    graph = build_graph()
    state = _make_initial_state(
        "What is the exact CO2 reduction per country per year from 2015–2025 "
        "broken down by sector with tonnage figures for all 195 UN member states?"
    )

    with pytest.raises(GraphRecursionError):
        graph.invoke(state, config={"recursion_limit": 6})


def test_graph_state_has_required_fields() -> None:
    """AgentState TypedDict must have all required fields."""
    state = _make_initial_state("test query")
    required_fields = [
        "query", "corpus_docs", "research_notes", "critique",
        "draft", "final_output", "iteration_count",
        "circuit_breaker_triggered", "messages",
    ]
    for field in required_fields:
        assert field in state, f"Missing required state field: {field}"
